pytest:
  stage: test
  image: "python:3.10"
  before_script:
  - python --version
  - pip install .[dev]
  - python -m ipykernel install --user --name py310
  script:
  - python -m pytest -W ignore -m "not memory_heavy and not requires_data"
  - python -m pytest -W ignore --nbmake ./docs
