# pre-commit configuration for fd-shifts
---

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black code formatting
        types: [python]
        args: [--safe, --config, pyproject.toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        types: [python]
        args: [--filter-files, --settings, pyproject.toml]
  
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        name: fix end of files
        
      - id: check-merge-conflict
        name: check for merge conflict strings
