defaults:
  - hydra/job_logging: disabled
  - data: cifar10_data.yaml #svhn_data.yaml
  - study: cifar_devries_study.yaml # svhn_confid_study.yaml



hydra:
  run:
    dir: ${exp.dir}
  output_subdir: hydra # hydra # needs to be null for manual testing!


exp:
  group_name: checks
  name: check_goback_seb # cifar10_run_0_sebastian
  version: None
  mode: train_test   # train or test
  work_dir: ${hydra:runtime.cwd}
  fold_dir: exp/${exp.fold}
  root_dir: ${env:EXPERIMENT_ROOT_DIR}
  data_root_dir: ${env:DATASET_ROOT_DIR}
  group_dir: ${env:EXPERIMENT_ROOT_DIR}/${exp.group_name}
  dir: ${exp.group_dir}/${exp.name}
  version_dir: ${exp.dir}/version_${exp.version}
  fold: 0 # call folds in launcher  via command line
  crossval_n_folds: 10
  crossval_ids_path: ${exp.dir}/crossval_ids.pickle
  output_paths:
    fit:
      raw_output: ${exp.version_dir}/raw_output.npy
      raw_output_dist: ${exp.version_dir}/raw_output_dist.npy
      external_confids: ${exp.version_dir}/external_confids.npy
      external_confids_dist: ${exp.version_dir}/external_confids_dist.npy
    test:
      raw_output: ${test.dir}/raw_output.npy
      raw_output_dist: ${test.dir}/raw_output_dist.npy
      external_confids: ${test.dir}/external_confids.npy
      external_confids_dist: ${test.dir}/external_confids_dist.npy
  log_path: ${exp.dir}/log.txt
  global_seed: 1 # set to False to disable deterministic training.





