defaults:
  - hydra/job_logging: disabled
  - data: cifar10_data.yaml #svhn_data.yaml
  - study: cifar_confid_study.yaml # svhn_confid_study.yaml



hydra:
  run:
    dir: ${exp.dir}
  output_subdir: null # hydra


exp:
  group_name: shifteval
  name: cifar10_run_0_sebastian
  version: None
  mode: test   # train or test
  work_dir: ${hydra:runtime.cwd}
  fold_dir: exp/${exp.fold}
  root_dir: ${env:EXPERIMENT_ROOT_DIR}
  group_dir: ${env:EXPERIMENT_ROOT_DIR}/${exp.group_name}
  dir: ${exp.group_dir}/${exp.name}
  version_dir: ${exp.dir}/version_${exp.version}
  fold: 0 # call folds in launcher  via command line
  crossval_n_folds: 10
  crossval_ids_path: ${exp.dir}/crossval_ids.pickle
  raw_output_path: ${exp.version_dir}/raw_output.npy
  external_confids_output_path: ${exp.version_dir}/external_confids.npy
  log_path: ${exp.dir}/log.txt
  global_seed: False # set to False to disable deterministic training.





