defaults:
  - hydra/job_logging: disabled
  - data: cifar100_data.yaml #svhn_data.yaml
  - study: cifar_confid_study.yaml # svhn_confid_study.yaml



hydra:
  run:
    dir: ${exp.dir}
  output_subdir: hydra





