# @package _global_
exp:
  group_name: chestxrayall_run_1
  name: chestxrayall_cross_entropy
trainer:
  num_epochs: 120
  val_every_n_epoch: 1
  # val splits:
  # - null: no validation set is created
  # - "devries": split the first 1000 cases of the iid test set as validation set
  # - cv: split 10% of the training set as validation set
  # - repro_confidnet: use the same cv split as Corbiere et al. 2020 (ConfidNet)
  val_split: "devries"
  do_val: True
  accelerator: None

  learning_rate: 0.0005
  optimizer:
    name: ADAM
    learning_rate: 0.0005
    momentum: 0.9
    nesterov: True
    weight_decay: 0

  lr_scheduler:
    name: "MultiStep" # "MultiStep" "CosineAnnealing"
    gamma: 0.1
    milestones: [100, 110] 
    max_epochs: ${trainer.num_epochs}
  momentum: 0.9
  weight_decay: 0
  batch_size: 12
  resume_from_ckpt: False
  benchmark: True # set to false if input size varies during training!
  fast_dev_run: False # True/Fals
  callbacks:
    model_checkpoint:
    confid_monitor:
    learning_rate_monitor:

model:
  name: cross_entropy #det_mcd_model
  fc_dim: 1024
  avg_pool: True
  dropout_rate: 0
  monitor_mcd_samples: 50 # only activated if "mcd" substring in train or val monitor confids.
  test_mcd_samples: 50 # only activated if "mcd" substring in test confids.
  network: 
    name: densenet121 #devries_and_enc      # confidnet_small_conv_and_enc / small_conv
    backbone: 
    imagenet_weights_path: # ${env:EXPERIMENT_ROOT_DIR}/pretrained_weights/vgg16-397923af.pth
    load_dg_backbone_path: #${exp.dir}/dg_backbone_2.ckpt  # ${env:EXPERIMENT_ROOT_DIR}/pretrained_weights/vgg16-397923af.pth
    save_dg_backbone_path:

test:
  name: test_results
  dir: ${exp.dir}/${test.name}
  cf_path: ${exp.dir}/hydra/config.yaml
  selection_criterion: latest # latest / best_failap_err
  selection_mode: #"latest" # model selection criterion or "latest"
  best_ckpt_path: ${exp.version_dir}/${test.selection_criterion}.ckpt # latest or best
  only_latest_version: True # if false looks for best metrics across all versions in exp_dir. Turn to false if resumed training.
  devries_repro_ood_split: False
  assim_ood_norm_flag: False
  iid_set_split: "devries" # all, devries


eval:
  performance_metrics:
    train: ["loss", "nll", "accuracy"] # train brier_score logging costs around 5% performance
    val: ["loss", "nll", "accuracy", "brier_score"]
    test: ["nll", "accuracy", "brier_score"]
  confid_metrics:
    train:
      ["failauc", "failap_suc", "failap_err", "fpr@95tpr", "e-aurc", "aurc"]
    val: ["failauc", "failap_suc", "failap_err", "fpr@95tpr", "e-aurc", "aurc"]
    test:
      [
        "failauc",
        "failap_suc",
        "failap_err",
        "mce",
        "ece",
        "e-aurc",
        "aurc",
        "fpr@95tpr",
      ]
  confidence_measures: # ["det_mcp" , "det_pe", "tcp" , "mcd_mcp", "mcd_pe", "mcd_ee", "mcd_mi", "mcd_sv"]
    train: ["det_mcp"] # mcd_confs not available due to performance. 'det_mcp' costs around 3% (hard to say more volatile)
    val: ["det_mcp"] # , "mcd_mcp", "mcd_pe", "mcd_ee", "mcd_mi", "mcd_sv"
    test:
      ["det_mcp", "det_pe", "mcd_mcp", "mcd_pe", "mcd_ee", "mcd_mi", "mcd_sv"]

  monitor_plots: #"calibration",
    [
      #"overconfidence",
      "hist_per_confid",
    ]

  tb_hparams: ["fold"]
  val_tuning: True
  ext_confid_name: "tcp"
  r_star: 0.25
  r_delta: 0.05

  query_studies: # iid_study, new_class_study, sub_class_study, noise_study
   iid_study: ${data.dataset}
   in_class_study:
