# @package _global_

defaults:
  - override /trainer/lr_scheduler: CosineAnnealingLR

exp:
  group_name: deepgamblers
  name: ${data.dataset}

trainer:
  num_epochs: 300
  dg_pretrain_epochs: 100

  optimizer:
    lr: 1e-1

model:
  name: devries_model
  fc_dim: 512
  dg_reward: 2.2
  avg_pool: True
  dropout_rate: 0
  monitor_mcd_samples: 50
  test_mcd_samples: 50
  budget: 0.3
  network:
    name: vgg13
    imagenet_weights_path:
    load_dg_backbone_path:
    save_dg_backbone_path: ${exp.dir}/dg_backbone.ckpt

eval:
  ext_confid_name: "dg"
