# @package _global_
defaults:
  - override /trainer/lr_scheduler: CosineAnnealingLR

exp:
  group_name: devries
  name: ${data.dataset}

trainer:
  num_epochs: 250
  lr_scheduler:
    T_max: ${trainer.num_epochs}
  optimizer:
    lr: 1e-1

model:
  name: devries_model
  fc_dim: 512
  dg_reward: 0
  avg_pool: True
  dropout_rate: 0
  monitor_mcd_samples: 50
  test_mcd_samples: 50
  budget: 0.3
  network:
    name: devries_and_enc
    backbone: vgg13
    imagenet_weights_path:
    load_dg_backbone_path:
    save_dg_backbone_path:

eval:
  ext_confid_name: "devries"
