# @package _global_
defaults:
  - override /trainer/lr_scheduler: LinearWarmupCosineAnnealingLR
  - override /trainer/optimizer: SGD
  - override /data: cifar10_384_data

exp:
  group_name: vit
  name: cifar10

trainer:
  num_epochs:
  num_steps: 40000
  optimizer:
    lr: 0.003
    momentum: 0.9
    weight_decay: 0.0

model:
  name: vit_model
  network:
    name: vit

eval:
  ext_confid_name: "maha"
