name: PyTest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          python -m ipykernel install --user --name py310
      - name: Test library
        run: |
          python -m pytest -W ignore -m "not memory_heavy and not requires_data"
      - name: Test docs
        run: |
          python -m pytest -W ignore --nbmake ./docs
